all: Mazemake Mazesolve

Mazemake: Mazemake.cpp dset.h
	g++ -g -Wall -o Mazemake Mazemake.cpp 

Mazesolve: Mazesolve.cpp
	g++ -g -Wall -o Mazesolve Mazesolve.cpp

clean:
	rm -f Mazemake
	rm -f Mazesolve
